### ISSUE TITLE
how to add a message when sending a freindship request

### ISSUE THREAD

**Issue by richtier** [revsys/django-friendship#36]
[models..py](https://github.com/revsys/django-friendship/blob/master/friendship/models.py#L71) as a field called `message` but, unless I am missing something, there is no way to use this field using `add_friend`

**Comment by ppawlak** [comment]
Unfortunately this created a bug:
if you call add_friend() with the same 2 users but with a different message it will raise an *IntegrityError* from the database instead of the expected *AlreadyExistsError*.

Example:

```
Friend.objects.add_friend(user1, user2, "Hi, I would like to be your friend")
Friend.objects.add_friend(user1, user2, "Pleeeeeease!")

IntegrityError: duplicate key value violates unique constraint "friendship_friendshiprequest_from_user_id_1b01d136f3677261_uniq"
DETAIL:  Key (from_user_id, to_user_id)=(1, 2) already exists.
```

I think you should write something like this to handle this situation:
```
        request, created = FriendshipRequest.objects.get_or_create(
            from_user=from_user,
            to_user=to_user            
        )

        if created is False:
            raise AlreadyExistsError("Friendship already requested")

        request.message=message
        request.save()
```

The drawback is it leads to an additional UPDATE query to the database.
Is there a better way ?

**Comment by frankwiles** [comment]
Thanks for reporting it.  Just fixed it!

**Comment by richtier** [comment]
I'm a but late to the party, but to save the writing to the database twice how about something like:
```
try:
       request = FriendshipRequest.objects.create(
            from_user=from_user,
            to_user=to_user,
            message=message,
        )
except IntegrityError:
    raise AlreadyExistsError("Friendship already requested")

```

**Comment by ppawlak** [comment]
+1 with @richtier code proposition as it seems more optimized

Speaking of the _add_friend_ method, I think it should also checks the 2 users are not already friends: that's what I first thought the _AlreadyExistsError_ was for. Moreover, this code also raise an _IntegrityError_:

```
r = Friend.objects.add_friend(user1, user2, "Hi, I would like to be your friend")
r.accept()
r2 = Friend.objects.add_friend(user1, user2, "Hi, I would like to be your friend")
r2.accept()
```

This issue was raised in #23, said to be fixed but it seems not.
