### ISSUE TITLE
DRF support

### ISSUE THREAD

**Issue by baneizalfe** [revsys/django-friendship#49]
Trying to use generics.ListCreateAPIView

For
`self.queryset = Follow.objects.following(request.user)`

I keep getting:
`django list object has no attribute order_by`

Follow.objects.following(request.user) works fine when directly adding to Serializer, but I would like to use ListAPIView Pagination for endless list.

**Comment by frankwiles** [comment]
Ah yes this is because many of those helper methods like `following` on the managers do not return QuerySets but instead returned cached objects for performance reasons. 

The solution is to look at the manager method and use the underlying Models themselves, so if you look at following here https://github.com/revsys/django-friendship/blob/master/friendship/models.py#L381 you'll see all that you need to really do is use:

  Follow.objects.filter(follower=request.user)

in your APIs.

**Comment by farice** [comment]
Is it only possible to return the pk of the objects? I cannot find a way to show the username as well. I am using DRF. 

```
class FriendViewSet(viewsets.ReadOnlyModelViewSet):
    serializer_class = FriendSerializer

    def get_queryset(self):
        return Friend.objects.filter(from_user=self.request.user)
```

**Comment by frankwiles** [comment]
Hi Farice, 

I'm confused on what you're asking here.  With DRF you can return any field you want.  However, to return django-friendship data the `model = Buddy` would likely need to be one of django-friendship's models.

**Comment by oalsing** [comment]
> Ah yes this is because many of those helper methods like `following` on the managers do not return QuerySets but instead returned cached objects for performance reasons.
> 
> The solution is to look at the manager method and use the underlying Models themselves, so if you look at following here https://github.com/revsys/django-friendship/blob/master/friendship/models.py#L381 you'll see all that you need to really do is use:
> 
> ```
> `Follow.objects.filter(follower=request.user)`
> ```
> 
> in your APIs.

Thanks a bunch Frank. I experienced some issues where the cache wouldn't be invalidated, returning funky responses. Using the underlying querysets solved it instantly.
