### ISSUE TITLE
Still supporting Django < 1.8?

### ISSUE THREAD

**Issue by econner** [revsys/django-friendship#55]
Is this project still supporting Django < 1.8?

**Comment by econner** [comment]
![image](https://cloud.githubusercontent.com/assets/527947/17003956/4bc38fbc-4e87-11e6-84b9-6600c32f47d3.png)
https://www.djangoproject.com/download/

**Comment by frankwiles** [comment]
We'll continue to support (and test against) those older versions until there is a reason no to do so.  While they aren't support any longer you would be surprised how many people are still running them, often internally.  

But if we need to drop support for a useful new feature or because 1.10 breaks the ability to continue support for <1.6, etc. we will happily.
